### ISSUE TITLE
Game is lagging terribly, and the menu is pink and black checkers. FPS is 0 to 16. Unplayable. 

### ISSUE THREAD

**Issue by LtChemist** [Migmag789/Migmodpacks#10]
I am having the issue where the menu is pink and black checkers. When the game finally shows up, it is lagging so bad and has the FPS on the screen as 0-16 basically. It is lagging so bad, and this is a brand new gaming laptop that costs over $2,000. I can play other modpacks, but this modpack is messing up right now which is sad because my favorite world is on it that I spent over five hours making.

**Comment by Migmag789** [comment]
Hey ! I know for the pink and black. But I don't know why you're lagging on this modpack and not the other ones. Try disabling BetterFPS. I don't know. And sorry :/
