### ISSUE TITLE
Embers alchemy quest is wrong (Beyond the skies)

### ISSUE THREAD

**Issue by SuperHostile** [Migmag789/Migmodpacks#12]
The Embers "Alchemy!" quest in Beyond the Skies is wrong:
![2018-12-08_11 17 39](https://user-images.githubusercontent.com/33268599/49684932-13193100-fadb-11e8-8535-c0beec9f742c.png)

To do alchemy in Embers, you need 1 Exchange Table and a minimum of 2 Alchemy Pedestals, not 4 Exchange Tables and 1 Alchemy Pedestal.

**Comment by Migmag789** [comment]
Oh, sorry, I'll fix that ! Thank you for reporting that. I'm not an Embers "pro" player, so I did not know that was like that. Thank you !
