### ISSUE TITLE
0 FPS

### ISSUE THREAD

**Issue by Calibos** [Migmag789/Migmodpacks#17]
For the modpack, please use labels !
Thank you for reporting a crash =)

vers. 1.9.3

Fps drops to basically 0, unable to play pack I had the same issue with, previous version 1.9.1
Tried adjusting betterfps options, removing betterFPS (which made it worse) no idea what's causing it

**Comment by Migmag789** [comment]
I don't know.. Sorry. Do you allowed enough RAM ? Do you have a good PC ?

**Comment by Calibos** [comment]
I allowed 12 gb of ram for the game, with another 12 for system, PC is really good, i'm running larger packs without issue

**Comment by Migmag789** [comment]
I don't know, i can't help you... Try the newer version, there's a chance to fix the bug ?

**Comment by Doomboom589** [comment]
try checking your gpu, it is quite common that there is an issue with that even though graphics cards are good enough

**Comment by Calibos** [comment]
No difficulties with any other pack, card indicates as undamaged 
    On Tuesday, April 30, 2019, 8:46:04 AM PDT, Doomboom589 <notifications@github.com> wrote:  
 
 
try checking your gpu, it is quite common that there is an issue with that even though graphics cards are good enough
