### ISSUE TITLE
Metallugic Infuser quest issue

### ISSUE THREAD

**Issue by Doomboom589** [Migmag789/Migmodpacks#18]
#13 Not really that sure how the tags work but my issue im having is that the metallugic infuser quest isnt detecting the quest s complete even though i remade the metallugic infuser and tried reloading the quest book. if there is anything you can do to fix it that would be great as me and my brother have really been getting into this pack!

**Comment by Migmag789** [comment]
I'll do that :D that's weird because it did not happen to me. At least try cheating to get the quest, because it unlocks a lot of things ;)
