### ISSUE TITLE
Transfer node

### ISSUE THREAD

**Issue by XDIAV** [Migmag789/Migmodpacks#20]
Hello,
i've got a problem the transfer node was not on jei but the filter is on it.
So it is a problem or you disable it.
Thanks for reading.

**Comment by Migmag789** [comment]
Hey ! Sorry for not answering that fast. That's normal for the transfer node not being on JEI, I disabled it. The filter is still on JEI because we can use it for many other things, like Trash Cans for example, which aren't disabled. Thanks for playing !
