### ISSUE TITLE
Mods not dropping items - Food / Skins - is dropping XP

### ISSUE THREAD

**Issue by JR8675309** [Migmag789/Migmodpacks#22]
Beyond the World 9 [FORGE] 

Mods not dropping items - Food / Skins - is dropping XP
[Modpacks](https://www.curseforge.com/minecraft/modpacks)
Last Updated: Sep 17, 2022
Game Version: 1.19.2   +1

please let me know what data you need 
i have not added or removed any mods, just key binds

**Comment by Migmag789** [comment]
Hi, I've been aware of this bug for a few days now, and I still don't know what's causing the issue. Still, thanks for reporting it! I'll do my best to fix it.
