### ISSUE TITLE
BTW9 v1.1 crashing on loading screen

### ISSUE THREAD

**Issue by willstickles** [Migmag789/Migmodpacks#23]
I can still play v1.0 with only the drops issue. v1.1 drops when the loading screen comes up. The crash log is the same every time.

	Crash Report UUID: bc9114c0-33a9-4358-a015-5a8677ae0e14
	FML: 43.1
	Forge: net.minecraftforge:43.1.52
	Flywheel Backend: Uninitialized
	FramedBlocks BlockEntity Warning: Not applicable
	Suspected Mods: Minecraft (minecraft)

**Comment by Migmag789** [comment]
Hi! I can't do anything if you don't give me the crash report

**Comment by willstickles** [comment]
[crash-2022-11-18_00.20.40-client.txt](https://github.com/Migmag789/Gravelteam/files/10044532/crash-2022-11-18_00.20.40-client.txt)

**Comment by Migmag789** [comment]
The mod that caused the crash is ChunkAnimator. I'm going to remove the mod from the pack, it looks like it does a lot of problems. Thanks for your report!
