### ISSUE TITLE
New update crash

### ISSUE THREAD

**Issue by Bworms1980** [Migmag789/Migmodpacks#5]
Hi

Not sure how to do this. I'm uploading the crash txt file, please let me know if that's correct. I installed the modpack today and when i start it, it begins to load, then after 20 seconds or so it crashes. I have already removed the modpack completely and tried a fresh install, but it still crashes.

[crash-2018-09-12_22.47.46-client.txt](https://github.com/Migmag789/Migmodpacks/files/2377535/crash-2018-09-12_22.47.46-client.txt)

**Comment by Migmag789** [comment]
That's a weird kind of crash. I don't really know how to help you but I have a question : Do you use a resource pack ? That says that need a texture for the menril berries from Integrated Dynamics. Thank you for reporting crashes by the way ! :D

**Comment by Bworms1980** [comment]
No, I hate texture packs lol. I tried to install the previous version and it crashed as well. I'll add that report here. I have no trouble with other packs. I'm only having crashes with one other new pack, but I can play other packs just fine.
[crash-2018-09-12_23.06.37-client.txt](https://github.com/Migmag789/Migmodpacks/files/2381375/crash-2018-09-12_23.06.37-client.txt)

**Comment by Migmag789** [comment]
Ok... That's really weird. Please unlock the modpack, update Integrated Dynamics and if that still crash I will make an issue on the Integrated Dynamics page. Btw I have another question : was VanillaFix on the update you use ? I can't remember because I'm working on the 1.7 of the modpack ^^

**Comment by Bworms1980** [comment]
Yes it has version: 

VanillaFix-1.0.9-97

and Integrated Dynamics is already up to date in modpack v.1.7

IntegratedDynamics-1.12.2-0.11.17

However, I updated Integregrated Dynamics in modpack v.1.6.3 and I can play the modpack now. 1.7 still crashes.

**Comment by Bworms1980** [comment]
Version 1.7 of Beyond the Skies already has the most up to date Integrated Dynamics is what I was trying to say above. Sorry if I confused you.

**Comment by Migmag789** [comment]
Oh ok... Sorry I don't speak english very well so I can't understand everytime... I'm really sorry ^^ By the way, that should fix the bug if you use the old java mc launcher or MultiMC I think. Thank you !

**Comment by Migmag789** [comment]
To be more organised, if you have always bugs with 1.7 please open a new issue ;)
