### ISSUE TITLE
Tweaks, mods and craft suggestions for Sand Factory !

### ISSUE THREAD

**Issue by Migmag789** [Migmag789/Migmodpacks#8]
In this issue, you can post everything about every kind of suggestions for Sand Factory. Feel free to suggest anything, even if it could look silly. Everyone makes mistakes!

**Comment by Maxipyke** [comment]
How a world we start with ?

**Comment by Migmag789** [comment]
Are you a beta tester ? If not, you don't have the modpack.

**Comment by Maxipyke** [comment]
I'm laughing.I'm a beta-tester.

**Comment by Migmag789** [comment]
Oh ok, just create a world with a template
