### ISSUE TITLE
Recipe Conflict - Fluid Dropper - Sky Resources 2

### ISSUE THREAD

**Issue by jbjmed** [Migmag789/Migmodpacks#9]
Hello, 
Looks like there is a recipe conflict between stone leggings and the fluid dropper. I see you have crafting ex on the pack, however I don't have the option to cycle between recipes. I simply made a recipe of 7 cobble and one wood plank to create it since its supposed to be a fairly early game recipe and well those are the materials I had. I suppose a clay bucket would work and make more sense than a wood plank.

**Comment by Migmag789** [comment]
o/ I'll work on a new recipe for that, or I'll just disable the stone armor of tiny progressions. Thank you for reporting it ! :)
